In [2]:
import numpy as np

In [5]:
test_1 = np.array([1,2,3])
test_2 = np.array([4,5,6])


print(np.concatenate((test_1,test_2)))

[1 2 3 4 5 6]


In [12]:
frst_dim = np.array([])
test_1 = np.array([1,2,3,4])

print(frst_dim)

frst_dim = np.append(0,test_1)

print(frst_dim)

frst_dim = np.append(test_1,0)

print(frst_dim)

[]
[0 1 2 3 4]
[1 2 3 4 0]


In [13]:
test_1 = [1,2,3,4,5]
print(test_1[0:2])

[1, 2]


In [14]:
import librosa
import soundfile as sf

# Load the FLAC file
flac_file_path = r'C:\Computer Science Programs\Fall_2024\EE502_BioMed\project\data\LibriSpeech\train-clean-100\26\496\26-496-0011.flac'  # Replace with your FLAC file path
wav_file_path = '../output_file.wav'   # Output WAV file path

# Load the audio file
audio_data, sample_rate = librosa.load(flac_file_path, sr=None)

# Save the audio data as a WAV file
sf.write(wav_file_path, audio_data, sample_rate)